### ISSUE TITLE
Generate broken Node `20.12.2`

### ISSUE THREAD

**Issue by ThornWalli** [basics/nuxt-booster#1000]
![image](https://github.com/basics/nuxt-booster/assets/8287751/c59d0d16-8a20-4c8b-95f1-c3506df40552)

**Comment by mauroviniciussilva** [comment]
I'm having the same issue in node `18.20.2`. 

Weird that it works in `18.17.0`.

**Comment by ThornWalli** [comment]
Already on it #1002

**Comment by ThornWalli** [comment]
@armenr @mauroviniciussilva 

It can be tested at `nuxt-booster@3.0.11-next.1`. 
Should work now.

**Comment by ThornWalli** [comment]
@armenr @mauroviniciussilva 

But now! `3.0.11-next.3`

**Comment by ThornWalli** [comment]
Think problem is fixed now 🙂, update will be next in `main` branch.
