### ISSUE TITLE
Disable lazy hydrate for specific routes

### ISSUE THREAD

**Issue by andrevferreiraa** [basics/nuxt-booster#1037]
Is it currently possible to disable the lazy-hydrate for specific pages? 

Most lazy hydrations already have this options so maybe it would be nice to have it here as well!

Many thanks

**Comment by ThornWalli** [comment]
Hello @andrevferreiraa,

Unfortunately, this is not possible in `speedkitHydrate` to change its behavior at runtime. 
https://github.com/basics/nuxt-booster/blob/main/src/runtime/hydrate.js

A LazyHydrate wrapper is used directly when it is called.

How do you register your components?

Do you use a plugin to register the component globally or do you integrate it directly into the pages?
Alternatively, the component would have to be integrated directly.

**Comment by ThornWalli** [comment]
Hello @andrevferreiraa,

with a new `vue` version there is now also the possibility to overwrite the hydrate.

I have an example of a route check in the documentation.

https://basics.github.io/nuxt-booster/composables/useBoosterHydrate.html#useful
