### ISSUE TITLE
poster maxresdefault is not found for some of my videos

### ISSUE THREAD

**Issue by cobraprojects** [basics/nuxt-booster#1044]
**Describe the bug**
if a video doesn't have `maxresdefault` poster I can't play the video

**To Reproduce**
- use `BoosterYoutube` component on this `https://www.youtube.com/watch?v=hAOgqC3IJ_A` video url
-  no image show plus the play button is 0 width and height

note: this video doesn't have `maxresdefault` poster size it has `hqdefault` and `default`.

**Expected behavior**
should fallback to hqdefault or be able to change the `poster_url` from the props

**Screenshots**
![image](https://github.com/basics/nuxt-booster/assets/42706279/3d9c05d5-6247-4dc6-998f-3f33244b2858)

**Desktop (please complete the following information):**
 - OS: Linux-ubuntu 24.04
 - Browser chrome,
 - Version 126.0.6478.114

**Comment by ThornWalli** [comment]
Hello @cobraprojects,

have you set the necessary `@nuxt/image` settings? (`domain`/`provider`)

```javascript
{
    image: {
      // The screen sizes predefined by `@nuxt/image`:
      screens: {
        default: 320,
        xxs: 480,
        xs: 576,
        sm: 768,
        md: 996,
        lg: 1200,
        xl: 1367,
        xxl: 1600,
        '4k': 1921
      },
      domains: [
        'https://picsum.photos',
        'https://img.youtube.com',
        'https://i.vimeocdn.com',
        'https://i.pickadummy.com'
      ],
      alias: {
        picsum: 'https://picsum.photos',
        youtube: 'https://img.youtube.com',
        vimeo: 'https://i.vimeocdn.com',
        pickadummy: 'https://i.pickadummy.com'
      }
    }
}
```

**Comment by cobraprojects** [comment]
> Hello @cobraprojects,
> 
> have you set the necessary `@nuxt/image` settings? (`domain`/`provider`)
> 

Yes I did

**Comment by ThornWalli** [comment]
Seems to be the Youtube video...

Video does not work: https://img.youtube.com/vi/hAOgqC3IJ_A/maxresdefault.jpg

Video works correctly: https://img.youtube.com/vi/cLKvbhfVBUU/maxresdefault.jpg

Considering the possibility of setting a fallback poster. Alternatively ignore poster, but then it doesn't look nice.

**Comment by cobraprojects** [comment]
@ThornWalli 
thanks for your time
I notice that any video doesn't have 1080p will have the same issue

**Comment by ThornWalli** [comment]
I'll close the issue 😉

![image](https://github.com/basics/nuxt-booster/assets/8287751/84dc8c05-f1b5-4915-90d1-6c08ad3d5309)

**Comment by ThornWalli** [comment]
Oohhh Sorry, got a bit confused here. Can open the issue again, personally don't see any other possibility than a fallback poster implementation.

Since it cannot be guaranteed that a poster is available for every video.

**Comment by cobraprojects** [comment]
thanks
What about adding a new prop for custom poster image URL

```
<booster-youtube
   poster_url="your_poster_url"
    ....
/>
```

if this prop exists use it otherwise use the normal behaviour

sorry I'm new to `vue js` world recently migrated from PHP
I'm not sure if I can create a pr with this

**Comment by ThornWalli** [comment]
@cobraprojects You can install the `next` version.

`npm i nuxt-booster@3.0.17-next.2`

There you now have a `posterSrc` property. An absolute path to a source in the `public` directory should be sufficient.

```js
const videoYoutube = {
  posterSrc: '/img/image-text-b.jpg',
  title: 'Youtube',
  url: 'https://www.youtube.com/watch?v=cLKvbhfVBUU',
  text: 'Nunc odio nisl dapibus consequat recusandae doloremque nisi natus repudiandae do accusantium corrupti. Harum quisquam, maxime, perspiciatis lobortis earum iure.'
};
```

**Comment by cobraprojects** [comment]
@ThornWalli 

> @cobraprojects You can install the `next` version.
> 
> `npm i nuxt-booster@3.0.17-next.2`
> 
> There you now have a `posterSrc` property. An absolute path to a source in the `public` directory should be sufficient.
> 
> ```js
> const videoYoutube = {
>   posterSrc: '/img/image-text-b.jpg',
>   title: 'Youtube',
>   url: 'https://www.youtube.com/watch?v=cLKvbhfVBUU',
>   text: 'Nunc odio nisl dapibus consequat recusandae doloremque nisi natus repudiandae do accusantium corrupti. Harum quisquam, maxime, perspiciatis lobortis earum iure.'
> };
> ```

I test it works fine thank you
I used it with `https://img.youtube.com/vi/${item.youtube_id}/hqdefault.jpg`
and it worked

the only issue now that it causes a layout shift

it jumps from 16/9 to 4/3

**Comment by ThornWalli** [comment]
Hello @cobraprojects,

wanted to announce that there will be another change when replacing the poster src ;)

Here you can see the before and after comparison: https://github.com/basics/nuxt-booster/blob/9aa869f8f8ef7f291ab2052e5ab9eccbbadff3fd/docs/src/migration/v3.1.0.md

**Comment by ThornWalli** [comment]
Issue is closed. Should be done for now, due to the possibility to overwrite the `src` from the poster.

https://basics.github.io/nuxt-booster/components/booster-youtube.html#postersources
