### ISSUE TITLE
Cannot import any of the booster components

### ISSUE THREAD

**Issue by umaraziz0** [basics/nuxt-booster#1112]
**Describe the bug**
I'm unable to import any of the booster components, as the import throws a `TS2307` error: `Cannot find module '#booster/components/BoosterPicture' or its corresponding type declarations.ts(2307)`. 

**To Reproduce**
1. Import a booster component
2. View the error on eslint or IDE

**Expected behavior**
Component should import properly

**Screenshots**
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/9d1f465e-c52c-4710-a0ca-66a2d59b1f0d">
<img width="254" alt="image" src="https://github.com/user-attachments/assets/f8bc4694-6d57-4656-abdb-1ab82b43a355">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1
 - Browser: Chrome
 - Version 

**Smartphone (please complete the following information):**
 not tested yet

**Additional context**
I have already installed and added the `nuxt-booster` module, here are some of my configurations:
```
"nuxt": "^3.12.4",
"nuxt-booster": "^3.1.5",
"vue": "^3.4.21",
````

My nuxt-booster config, a simplified version of the template from the docs:
```
booster: {
    performanceMetrics: {
      device: {
        hardwareConcurrency: { min: 2, max: 48 },
        deviceMemory: { min: 2 },
      },
      timing: {
        fcp: 800,
        dcl: 1200, // fallback if fcp is not available (safari)
      },
    },

    componentAutoImport: false,
    componentPrefix: undefined,

    /**
     * IntersectionObserver rootMargin for Components and Assets
     */
    lazyOffset: {
      component: '0%',
      asset: '0%',
    },
  },

**Comment by ThornWalli** [comment]
Hello @umaraziz0,

have you also added the module to the `nuxt.config`?

```js
{
  modules: ['nuxt-booster']
}
```

**Comment by umaraziz0** [comment]
Hello @ThornWalli , thanks for replying. Yes I have added the module to my `nuxt.config` file, double-checked this. 

Here is a list of my modules and plugins for more context:
```
modules: [
    '@nuxt/eslint',
    '@nuxtjs/tailwindcss',
    '@nuxt/image',
    '@nuxt/fonts',
    '@nuxtjs/seo',
    'nuxt-security',
    '@nuxt/scripts',
    'nuxt-gtag',
    '@nuxtjs/html-validator',
    '@vueuse/nuxt',
    'dayjs-nuxt',
    'shadcn-nuxt',
    'nuxt-swiper',
    '@formkit/auto-animate/nuxt',
    'nuxt-aos',
    'nuxt-laravel-precognition',
    'vue-recaptcha/nuxt',
    'nuxt-booster',
    'nuxt-delay-hydration',
  ],

  plugins: ['~/plugins/nuxt-laravel-precognition.ts', '~/plugins/vue-google-map.ts'],

  build: {
    analyze: isDev,
    transpile: [
      '@fortawesome/vue-fontawesome',
      '@fortawesome/fontawesome-svg-core',
      '@fortawesome/free-solid-svg-icons',
      '@fortawesome/free-regular-svg-icons',
      '@fortawesome/pro-solid-svg-icons',
      '@fortawesome/pro-regular-svg-icons',
      '@fortawesome/free-brands-svg-icons',
      'vue-google-maps-community-fork',
      '@googlemaps/markerclusterer',
    ],
  },

**Comment by ThornWalli** [comment]
Hello @umaraziz0,

very strange, it seems that you are missing alias definitions.

Could you put a `console.log` in the file `./node_modules/nuxt-booster/dist/module.mjs` line ~708?

![image](https://github.com/user-attachments/assets/75522b71-b641-406e-aa5e-1eb4b10872cd)

It can't be that it can't find the import if the alias is set.

**Comment by ThornWalli** [comment]
https://github.com/basics/nuxt-booster/issues/1112

**Comment by umaraziz0** [comment]
> Hello @umaraziz0,
> 
> very strange, it seems that you are missing alias definitions.
> 
> Could you put a `console.log` in the file `./node_modules/nuxt-booster/dist/module.mjs` line ~708?
> 
> ![image](https://private-user-images.githubusercontent.com/8287751/363913471-75522b71-b641-406e-aa5e-1eb4b10872cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzIxMDAsIm5iZiI6MTcyNTUzMTgwMCwicGF0aCI6Ii84Mjg3NzUxLzM2MzkxMzQ3MS03NTUyMmI3MS1iNjQxLTQwNmUtYWE1ZS0xZWI0YjEwODcyY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTAyMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIxODhmODRhNWYyYWRkMmFkYTJjNWNmZmU5YzdiMGRlMDVkNzllZjY1ZWI3OWQxODJhZmZkNjlkYmFhMzNmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AKGaLRiVl0JO6qxeNommZjFeKPq04St-N3q62mKhZbU)
> 
> It can't be that it can't find the import if the alias is set.

Hello, I tried this, but unfortunately nothing came out in the console. 


> Hello @umaraziz0,
> 
> I think I found the problem...
> 
> [nuxt/module-builder#349](https://github.com/nuxt/module-builder/issues/349)

I see, is there any workaround that I can do in the meantime?

**Comment by ThornWalli** [comment]
@umaraziz0 Try this version 😉

`npm i nuxt-booster@3.1.6-next.1`

**Comment by umaraziz0** [comment]
> @umaraziz0 Try this version 😉
> 
> `npm i nuxt-booster@3.1.6-next.1`

Still the same issue, unfortunately 

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/cc0922f2-3645-4167-bda0-70f70dd4065e">

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/8d020296-2074-4b41-bde7-b0ae86bb2841">

**Comment by ThornWalli** [comment]
What does your “runtime” folder look like in the `node_modules/nuxt-booster`?

![image](https://github.com/user-attachments/assets/086859d3-edb1-49c4-ad62-b47dfcb411f9)

What does your typescript config look like?

**Comment by umaraziz0** [comment]
> What does your “runtime” folder look like in the `node_modules/nuxt-booster`?
> 
> ![image](https://private-user-images.githubusercontent.com/8287751/364760297-086859d3-edb1-49c4-ad62-b47dfcb411f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzY3OTgsIm5iZiI6MTcyNTUzNjQ5OCwicGF0aCI6Ii84Mjg3NzUxLzM2NDc2MDI5Ny0wODY4NTlkMy1lZGIxLTQ5YzQtYWQ2Mi1iNDdkZmNiNDExZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTE0MTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNjNTRlMjk1YjMyY2ZkOGY5NTM1ZTU4ZmIxNzVkZDEwZWJjNjNiMWI1YmY5MjgxOTgxYTQ0NWQ2YjQ5MWZmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c3J0m2hL7Q6prflC_W5o6KOCnIjiu5H9y60aE0_qL_A)
> 
> What does your typescript config look like?

Here it is, seems to still be missing the `d.ts` files

<img width="335" alt="image" src="https://github.com/user-attachments/assets/8a6a81e7-eed0-4ab4-9c10-d2566263fa55">

My tsconfig just extends nuxt's `tsconfig.server.json`, which I think is the default behavior. Haven't made any changes:

```
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noEmit": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "allowJs": true,
    "resolveJsonModule": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "paths": {
      "#imports": [
        "./types/nitro-imports"
      ],
      "~/*": [
        "../*",
        "../*"
      ],
      "@/*": [
        "../*",
        "../*"
      ],
      "~~/*": [
        "../*",
        "../*"
      ],
      "@@/*": [
        "../*",
        "../*"
      ],
      "nitropack": [
        "../node_modules/nitropack"
      ],
      "defu": [
        "../node_modules/defu"
      ],
      "h3": [
        "../node_modules/h3"
      ],
      "consola": [
        "../node_modules/consola"
      ],
      "ofetch": [
        "../node_modules/ofetch"
      ],
      "@unhead/vue": [
        "../node_modules/@unhead/vue"
      ],
      "@nuxt/devtools": [
        "../node_modules/@nuxt/devtools"
      ],
      "@vue/runtime-core": [
        "../node_modules/@vue/runtime-core"
      ],
      "@vue/compiler-sfc": [
        "../node_modules/@vue/compiler-sfc"
      ],
      "unplugin-vue-router/client": [
        "../node_modules/unplugin-vue-router/client"
      ],
      "@nuxt/schema": [
        "../node_modules/@nuxt/schema"
      ],
      "nuxt": [
        "../node_modules/nuxt"
      ],
      "#internal/nuxt/paths": [
        "../node_modules/nuxt/dist/core/runtime/nitro/paths"
      ],
      "~": [
        "./.."
      ],
      "@": [
        "./.."
      ],
      "~~": [
        "./.."
      ],
      "@@": [
        "./.."
      ],
      "assets": [
        "../assets"
      ],
      "assets/*": [
        "../assets/*"
      ],
      "public": [
        "../public"
      ],
      "public/*": [
        "../public/*"
      ],
      "#image": [
        "../node_modules/@nuxt/image/dist/runtime"
      ],
      "#image/*": [
        "../node_modules/@nuxt/image/dist/runtime/*"
      ],
      "#sitemap": [
        "../node_modules/@nuxtjs/sitemap/dist/runtime/types"
      ],
      "#nuxt-scripts-validator": [
        "../node_modules/@nuxt/scripts/dist/runtime/validation/valibot"
      ],
      "#nuxt-scripts": [
        "../node_modules/@nuxt/scripts/dist/runtime/types"
      ],
      "#nuxt-scripts-utils": [
        "../node_modules/@nuxt/scripts/dist/runtime/utils"
      ],
      "#dayjs": [
        "../node_modules/dayjs-nuxt/dist/runtime/composables/dayjs"
      ],
      "#aos": [
        "../node_modules/nuxt-aos/dist/runtime"
      ],
      "#aos/*": [
        "../node_modules/nuxt-aos/dist/runtime/*"
      ],
      "#booster": [
        "../node_modules/nuxt-booster/dist/runtime"
      ],
      "#booster/*": [
        "../node_modules/nuxt-booster/dist/runtime/*"
      ],
      "#nuxt-delay-hydration/api": [
        "./delay-hydration"
      ],
      "#vue-router": [
        "./vue-router"
      ],
      "#internal/nuxt-site-config": [
        "../node_modules/nuxt-site-config/dist/runtime/nitro/composables"
      ],
      "#internal/nuxt-site-config/*": [
        "../node_modules/nuxt-site-config/dist/runtime/nitro/composables/*"
      ],
      "#internal/nuxt-simple-robots": [
        "../node_modules/@nuxtjs/robots/dist/runtime/nitro/composables"
      ],
      "#internal/nuxt-simple-robots/*": [
        "../node_modules/@nuxtjs/robots/dist/runtime/nitro/composables/*"
      ],
      "#internal/nuxt-robots": [
        "../node_modules/@nuxtjs/robots/dist/runtime/nitro/composables"
      ],
      "#internal/nuxt-robots/*": [
        "../node_modules/@nuxtjs/robots/dist/runtime/nitro/composables/*"
      ],
      "#content/server": [
        "../node_modules/nuxt-link-checker/dist/runtime/nitro/composables/content-mock"
      ],
      "#link-checker/pure": [
        "../node_modules/nuxt-link-checker/dist/runtime/pure"
      ],
      "#link-checker/pure/*": [
        "../node_modules/nuxt-link-checker/dist/runtime/pure/*"
      ]
    },
    "lib": [
      "esnext",
      "webworker",
      "dom.iterable"
    ]
  },
  "include": [
    "./types/nitro-nuxt.d.ts",
    "../node_modules/@nuxt/eslint/runtime/server",
    "../node_modules/@nuxtjs/tailwindcss/runtime/server",
    "../node_modules/@nuxt/image/runtime/server",
    "../node_modules/@nuxt/fonts/runtime/server",
    "../node_modules/nuxt-site-config/dist/module.mjs/runtime/server",
    "../node_modules/@nuxtjs/robots/dist/module.mjs/runtime/server",
    "../node_modules/@nuxtjs/sitemap/dist/module.mjs/runtime/server",
    "../node_modules/nuxt-og-image/dist/module.mjs/runtime/server",
    "../node_modules/nuxt-schema-org/dist/module.mjs/runtime/server",
    "../node_modules/nuxt-seo-experiments/dist/module.mjs/runtime/server",
    "../node_modules/nuxt-link-checker/dist/module.mjs/runtime/server",
    "../node_modules/@nuxtjs/seo/runtime/server",
    "../node_modules/nuxt-security/runtime/server",
    "../node_modules/@nuxt/scripts/runtime/server",
    "../node_modules/nuxt-gtag/runtime/server",
    "../node_modules/@nuxtjs/html-validator/runtime/server",
    "../node_modules/@vueuse/nuxt/runtime/server",
    "../node_modules/dayjs-nuxt/runtime/server",
    "../node_modules/shadcn-nuxt/runtime/server",
    "../node_modules/nuxt-swiper/runtime/server",
    "../node_modules/@formkit/auto-animate/nuxt/runtime/server",
    "../node_modules/nuxt-aos/runtime/server",
    "../node_modules/nuxt-laravel-precognition/runtime/server",
    "../../runtime/server",
    "../node_modules/@nuxtjs/fontaine/runtime/server",
    "../node_modules/nuxt-booster/runtime/server",
    "../node_modules/nuxt-delay-hydration/runtime/server",
    "../node_modules/@nuxt/devtools/runtime/server",
    "../node_modules/@nuxt/telemetry/runtime/server",
    "./module/nuxt-site-config.d.ts",
    "./module/nuxt-robots.d.ts",
    "./module/@nuxtjs-sitemap.d.ts",
    "./types/nitro.d.ts",
    "../**/*",
    "../server/**/*"
  ],
  "exclude": [
    "../node_modules",
    "../node_modules/nuxt/node_modules",
    "../node_modules/nuxt-site-config/dist/node_modules",
    "../node_modules/@nuxtjs/robots/dist/node_modules",
    "../node_modules/@nuxtjs/sitemap/dist/node_modules",
    "../node_modules/nuxt-og-image/dist/node_modules",
    "../node_modules/nuxt-schema-org/dist/node_modules",
    "../node_modules/nuxt-seo-experiments/dist/node_modules",
    "../node_modules/nuxt-link-checker/dist/node_modules",
    "../dist"
  ]
}

**Comment by umaraziz0** [comment]
Update: I did a wipe of the `node_modules` folder and the `d.ts` files seems to be here now, but still having the same error

<img width="335" alt="image" src="https://github.com/user-attachments/assets/d931eb91-66d5-49c8-83f7-2ec4200e88ac">

**Comment by ThornWalli** [comment]
@umaraziz0 Can you try to make an import from @nuxt/image?

And see if you get the same message. To narrow down the error.

e.g. `import NuxtPicture from '#image/components/NuxtPicture';`

I think it should all be there.

**Comment by umaraziz0** [comment]
> import NuxtPicture from '#image/components/NuxtPicture';

Yep, gives me the same error. I've been relying on nuxt image's auto import, so I never had to manually import their components before

<img width="935" alt="image" src="https://github.com/user-attachments/assets/fffac2d5-f3ff-49d9-846e-be8c69c8d459">

**Comment by ThornWalli** [comment]
@umaraziz0 Could you perhaps provide a small project to reproduce?

I can't reproduce it right now...

**Comment by umaraziz0** [comment]
@ThornWalli working on a company project right now so I might not be able to create an exact reproduction, but I'll see if i can recreate in another repo
