### ISSUE TITLE
"useBoosterHydrate" is not defined

### ISSUE THREAD

**Issue by tlkiong** [basics/nuxt-booster#1153]
**Describe the bug**

Using
- nuxt 3.12.4
- nuxt booster: 3.1.6

In nuxt.config.ts

```
modules: [
  ...,
  'nuxt-booster',
],
booster: {
  detection: {
    performance: true,
    browserSupport: true,
  },

  performanceMetrics: {
    device: {
      hardwareConcurrency: { min: 2, max: 48 },
      deviceMemory: { min: 2 },
    },
    timing: {
      fcp: 800,
      dcl: 1200,
    },
  },

  componentAutoImport: false,
  componentPrefix: undefined,

  /**
   * IntersectionObserver rootMargin for Compoennts and Assets
   */
  lazyOffset: {
    component: '0%',
    asset: '0%',
  },
},
```

In a "pages" file:

```javascript
const hydrate = useBoosterHydrate()
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ThornWalli** [comment]
I'm closing the issue, if there is anything else you can open it again.
