### ISSUE TITLE
error in safari browser Version 17.1.2 

### ISSUE THREAD

**Issue by omareyad** [basics/nuxt-booster#1178]
**Describe the bug**
i'm create new project 
npx nuxi@latest app 
and install nuxt-booster 
this is my nuxt.config.ts 
 modules: ['nuxt-booster'],
  booster: {
    performanceMetrics: {
      device: {
        hardwareConcurrency: { min: 2, max: 48 },
        deviceMemory: { min: 2 },
      },
      timing: {
        fcp: 800,
        dcl: 1200, // fallback if fcp is not available (safari)
      },
    },
but in safari browser in console log 

Unhandled Promise Rejection: TypeError: Promise.withResolvers is not a function. (In 'Promise.withResolvers()', 'Promise.withResolvers' is undefined)
waitForVisibilty entry.js 77

-This error causes the page not to load 
Safari or even iPhone .
- But on Chrome it works .

<img width="484" alt="Screenshot 2024-12-27 at 8 49 16 PM" src="https://github.com/user-attachments/assets/da013074-d4fb-47c1-8ac9-9e87b216804f" />

<img width="532" alt="Screenshot 2024-12-27 at 8 49 10 PM" src="https://github.com/user-attachments/assets/22fa9c07-4418-47b1-90db-4e50b70c8545" />

<img width="540" alt="Screenshot 2024-12-27 at 8 51 25 PM" src="https://github.com/user-attachments/assets/454cdda4-e38c-4d2d-8b65-22b2067af60d" />

<img width="663" alt="Screenshot 2024-12-27 at 8 52 01 PM" src="https://github.com/user-attachments/assets/80c68a7a-de99-4c9f-821a-aad36b55ad34" />

The project is new and does not contain any lines of code or any libraries  just nuxt-booster .

**Comment by StirStudios** [comment]
We get this same plus on build we are getting this as well

```
Could not load nuxt-booster. Is it installed?
```

iPhone with Safari is not loading images or scripts correctly.

**Comment by StirStudios** [comment]
Same with version: Version 17.6 (19618.3.11.11.5)

**Comment by ThornWalli** [comment]
Hello @omareyad,

you can install the latest version. `npm i nuxt-booster@latest`

I have removed the `Promise.withResolvers()`

**Comment by omareyad** [comment]
Yes ,  I'm installed this version  "nuxt-booster": "^3.1.6-next.1", 
It worked well on Safari and iPhone .
Should I stay on this version or do I install the latest version? -> npm i nuxt-booster@latest ?

**Comment by ThornWalli** [comment]
You can use the `next` version or switch to `latest`.

Your fix is already in the `main` (`latest`) 😉

**Comment by omareyad** [comment]
I've used the latest version and things look good , thank U @ThornWalli
