### ISSUE TITLE
[Progress] `nuxt@3` support

### ISSUE THREAD

**Issue by ThornWalli** [basics/nuxt-booster#542]
Nuxt 3 version is available 🎉

[V3 Docs](https://nuxt-booster.grabarzundpartner.dev/v3)

> ⚠️ **Important:** `nuxt-booster` was prepared for `vite` and `webpack`. 
But unfortunately there are different results between the builders, 
because with the webpack build feature (e.g. `Inline Styles`) are missing.

## Install

```
npm i nuxt-booster
```

### General

- [x] Docs
- [x] How is the `crossorigin` handled in `nuxt@3`? (e.g. `anonymous`, `use-credentials`)
_Is set via the module option `crossorigin`._

### Entry integration
- [x] Vite
- [x] Webpack

### Preload optimization
  - [x] ~Resource Manifest optimization~ Reduce preloads, prefetches per generate HTML manipulation
    - [x] ~https://github.com/nuxt/nuxt.js/issues/14362~

### Embedded CSS
- [x] Vite
- [x] Webpack

### Plugin
  - [x] Import Fonts CSS (e.g. @font-face)
    - [x] Direct import. (e.g. `import './fonts.css';`)
      - [x] https://github.com/nuxt/nuxt/issues/21383
    - [x]  Workaround via `useHead` and fonts script.
  - [x] Directive - `v-font`
    - [x] https://github.com/nuxt/nuxt.js/issues/15424
  - [x] Provides
    - [x] `$booster`
    - [x] `$getFont`
  - [x] Replace Mixins with Composable.
    - [x] Head description based on the `FontCollection`
      - [x] TagPriority (https://unhead.harlanzw.com/guide/guides/sorting)
    - [x] Critical flag `inject`/`provide`

### Image (`BoosterPicture`/`BoosterImage`)
- [x] `@nuxt/image` https://github.com/nuxt/image/discussions/548

#### Helper

- [x] `boosterHydrate`
  - [x] replace `vue-lazy-hydration` with `vue3-lazy-hydration` 

#### Components

- [x] `BoosterLayer`  
- [x] `BoosterImage`
- [x] `BoosterPicture`
- [x] `BoosterVimeo`
- [x] `BoosterYoutube`
- [x] `BoosterIframe`
- [x] WeakHardwareOverlay

**Removed Components**

- [x] ~~`abstracts/ComponentObserver`~~ 
  - Composable: `#booster/composables/componentObserver`
- [x] ~~`abstracts/OnlySsr`~~
- [x] ~~`GoogleLighthouse`~~

### Tests
  - [x] replaced `jest` with `vitest`

**Comment by everyx** [comment]
@ThornWalli Can we separate the `SpeedkitXXX` components from this plugin? so we can use them in combination and let the Speedkit plugin adapt to Nuxt 3 without waiting for `nuxt/image` to adapt to nuxt 3, and all new projects based on nuxt 3 could use and test this plugin as early as possible

**Comment by nathanchase** [comment]
> @ThornWalli Can we separate the `SpeedkitXXX` components from this plugin? so we can use them in combination and let the Speedkit plugin adapt to Nuxt 3 without waiting for `nuxt/image` to adapt to nuxt 3, and all new projects based on nuxt 3 could use and test this plugin as early as possible

There is a new version of image available and working for Nuxt 3 now:
https://v1.image.nuxtjs.org/
`"@nuxt/image-edge": "1.0.0-27628766.3629b9a"`

**Comment by yangwao** [comment]
Hey, we at https://github.com/kodadot/nft-gallery plan to use nuxt-speedkit and we are in process migration from nuxt2 to nuxt3, step by step, not fastest, but just want to make sure you are heading there too. 

I'm happy to donate something, if that would speed up things on your side. 
Probably I'm not only one who would use it in Nuxt3 :)

Let me know!

**Comment by ThornWalli** [comment]
Hi @Yangwao,

unfortunately we ran into a Vue3 bug right at the beginning ;)
We are on it, but have stones on the way :)

**Comment by StephanGerbeth** [comment]
@yangwao currently we are waiting for the following pull request from Linus Borg to be released. You can help us to increase the pressure here ;) : https://github.com/vuejs/core/issues/7499

We are of course also happy about donations, but currently we cannot pursue the integration in Nuxt3 as long as this pull request has not been accepted.

**Comment by yangwao** [comment]
> We are of course also happy about donations

uWu
<img src="https://media4.giphy.com/media/28AEi3TIvtSP6/giphy.gif"/>

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/5887929/73d9676c-380d-45fe-9cdf-3178af2fdb33)

**Comment by sbastias** [comment]
Node v19.9.0
NuxtJS v3.6.1

Deleted all node_modules
yarn cache clear
rm yarn.lock

Getting the following error on yarn:

```
ℹ [nuxt-speedkit] added module @nuxtjs/critters, for more configuration learn more at https://github.com/nuxt-modules/critters                                                                                                                                                                                                          nuxt-speedkit 1:38:38 AM
ℹ [nuxt-speedkit] added module @nuxtjs/fontaine, for more configuration learn more at https://github.com/nuxt-modules/fontaine                                                                                                                                                                                                          nuxt-speedkit 1:38:38 AM
ℹ [nuxt-speedkit] added module @nuxt/image, for more configuration learn more at https://image.nuxtjs.org/setup#configure                                                                                                                                                                                                               nuxt-speedkit 1:38:38 AM

 ERROR  Cannot read properties of undefined (reading 'map')                                                                                                                                                                                                                                                                                            1:38:38 AM

  at getVariances (node_modules/nuxt-speedkit/dist/module.mjs:55:25)
  at node_modules/nuxt-speedkit/dist/module.mjs:36:20
  at Array.map (<anonymous>)
  at FontConfig.toJSON (node_modules/nuxt-speedkit/dist/module.mjs:34:23)
  at prepareFontsConfiguartion (node_modules/nuxt-speedkit/dist/module.mjs:257:28)
  at getFontConfigTemplate (node_modules/nuxt-speedkit/dist/module.mjs:285:30)
  at addBuildTemplates (node_modules/nuxt-speedkit/dist/module.mjs:456:25)
  at async setup (node_modules/nuxt-speedkit/dist/module.mjs:436:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:95)

error Command failed with exit code 1.
```

**Comment by StephanGerbeth** [comment]
@yangwao thank you very much. We were very happy about your donation. As you can see, we have already started the migration. The big part is already done. We are currently fine-tuning the details so that we can also guarantee efficient loading of resources with Nuxt3.

**Comment by ThornWalli** [comment]
Nuxt 3 version in now released. 🎉

Nuxt 2 is no longer maintained, but can still be installed via `nuxt-booster@2`.
