### ISSUE TITLE
Website performance decreases after integrating nuxt-speedkit in nuxt 3

### ISSUE THREAD

**Issue by muhammad-grayphite** [basics/nuxt-booster#824]
**Describe the bug**
We recentlu upgraded our project to nuxt 3 and working on its performance. We were using this library in nuxt 2 as well where it shows impressive increase in performance but in nuxt 3 its very strange it decreases the site performance. Other strange thing is its only happening on desktop.
There is a flicker in website loading which is causing this issue called **Cumulative Layout Shift** which only happen after integrating nuxt-speedkit. I am attaching the screenshots taken from Google page Speed Insight as well as gif of the site loading with and without nuxt-speedkit. Its a big project I can't share the codebase. here my package.json 
```    
"@nuxt/image-edge": "^1.0.0-28099902.2b6ed1c",
"nuxt": "^3.5.3",
"nuxt-speedkit": "^3.0.0-next.17",
```
and configurations in nuxt.config.ts
```
  speedkit: {

    detection: {
      performance: true,
      browserSupport: true
    },

    performanceMetrics: {
      device: {
        hardwareConcurrency: { min: 2, max: 48 },
        deviceMemory: { min: 2 }
      },
      timing: {
        fcp: 800,
        dcl: 1200
      }
    },

    fonts: [
      {
        family: 'Lato',
        locals: ['Lato'],
        fallback: ['Roboto', 'sans-serif'],
        variances: [
          {
            style: 'normal',
            weight: 400,
            sources: [
              { src: '@/assets/fonts/lato-v22-latin-regular.woff', type: 'woff' },
              { src: '@/assets/fonts/lato-v22-latin-regular.woff2', type: 'woff2' }
            ]
          },
          {
            style: 'normal',
            weight: 700,
            sources: [
              { src: '@/assets/fonts/lato-v22-latin-700.woff', type: 'woff' },
              { src: '@/assets/fonts/lato-v22-latin-700.woff2', type: 'woff2' }
            ]
          }
        ]
      },
      {
        family: 'Khand',
        locals: ['Khand'],
        fallback: ['Roboto', 'sans-serif'],
        variances: [
          {
            style: 'normal',
            weight: 600,
            sources: [
              { src: '@/assets/fonts/khand-v12-latin-600.woff', type: 'woff' },
              { src: '@/assets/fonts/khand-v12-latin-600.woff2', type: 'woff2' }
            ]
          }
        ]
      },
      {
        family: 'Allerta Stencil',
        locals: ['Allerta Stencil'],
        fallback: ['Roboto', 'sans-serif'],
        variances: [
          {
            style: 'normal',
            weight: 400,
            sources: [
              { src: '@/assets/fonts/allerta-stencil-v16-latin-regular.woff', type: 'woff' },
              { src: '@/assets/fonts/allerta-stencil-v16-latin-regular.woff2', type: 'woff2' }
            ]
          }
        ]
      },
      {
        family: 'Caveat',
        locals: ['Caveat'],
        fallback: ['Roboto', 'sans-serif'],
        variances: [
          {
            style: 'normal',
            weight: 700,
            sources: [
              { src: '@/assets/fonts/caveat-v14-latin-700.woff', type: 'woff' },
              { src: '@/assets/fonts/caveat-v14-latin-700.woff2', type: 'woff2' }
            ]
          }
        ]
      },
      {
        family: 'Poppins',
        locals: ['Poppins'],
        fallback: ['Roboto', 'sans-serif'],
        variances: [
          {
            style: 'normal',
            weight: 400,
            sources: [
              { src: '@/assets/fonts/poppins-v19-latin-regular.woff', type: 'woff' },
              { src: '@/assets/fonts/poppins-v19-latin-regular.woff2', type: 'woff2' }
            ]
          }
        ]
      }
    ],

    componentAutoImport: false,
    componentPrefix: undefined,

    /**
     * IntersectionObserver rootMargin for Compoennts and Assets
     */
    lazyOffset: {
      component: '0%',
      asset: '0%'
    },

    loader: {
      dataUri: null,
      size: '100px',
      backgroundColor: 'grey'
    }

  },

  image: {
    screens: {
      default: 320,
      xxs: 480,
      xs: 576,
      sm: 768,
      md: 996,
      lg: 1200,
      xl: 1367,
      xxl: 1600,
      '4k': 1921
    },

    domains: ['img.youtube.com', 'i.vimeocdn.com'],

    alias: {
      youtube: 'https://img.youtube.com',
      vimeo: 'https://i.vimeocdn.com',
    }
  },
```

**To Reproduce**
1. Go to [https://lahore-preprod-nuxt3-speedkit.netlify.app/](url)
2. you'll see the weired flicker

**Expected behavior**
when load or reload the site it should be smooth. not this flicker. 
this deployment link is without this nuxt-speedkit [https://lahore-preprod-nuxt3.netlify.app/](url)

**Screenshots**
With nuxt-speedkit:
<img width="1228" alt="with nuxt-speedkit" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/85872908/5b21b734-0257-4c93-b21d-7c29d2443ce2">
and without nuxt-speedkit:
<img width="1231" alt="without nuxt-speedkit" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/85872908/c3e4a20b-b5bb-4f16-aa5f-643fce452d1e">
Other than **Cumulative Layout Shift** it seems to be good.

**Desktop (please complete the following information):**
 - OS: Mac, Linux
 - Browsers: Chrome, Firefox, Safari(a little)
 - Latest Version

**Smartphone (please complete the following information):**
 on mobile phone this is working pefectly and there is massive performance increase

**Additional context**
Here is the gif with nuxt-speedkit:
![layout_shift_issue](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/85872908/71ce9f7d-4a37-4e33-aae8-ec0381d24049)
and without this package loading is smooth on desktop:
![no_layout_issue](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/85872908/286d1973-a086-40a6-be52-7a3f719d32f4)

**Comment by ThornWalli** [comment]
Hello @muhammad-grayphite,

looks like the exchange vnode takes quite long.

According to your network you also have pretty big files 😉

Example: `entry.f071e693.js` -> `307kb`

But this should be solved with asynchronous imports.

This can help you to visualize the chunks https://nuxt.com/docs/api/configuration/nuxt-config#analyze

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/8287751/6744a4ee-3963-4d0c-91db-947aadba5848)

**Background why the CSS is missing between times:**
Our goal is that initially no CSS is loaded, but is already in the HTML. 
For this we use in Nuxt 3 the module "https://github.com/nuxt-modules/critters".

We remove with the option `preloadOptimize` unnecessary style/script (prefetchs/preloads) tags from the generated HTML files.

https://github.com/GrabarzUndPartner/nuxt-speedkit/blob/14a9ceb79671cfd428c49f9b3f569db8e88f07c2/src/utils/preload.mjs#L11-L27

The CSS of the header is added later and the StyleBlock is replaced. 
For this the resources are responsible which still need something with the load, can this unfortunately at present not re-enact, since `nuxt@3` for us is not yet productively usable.

**Comment by StirStudios** [comment]
@ThornWalli I thought I would tag my questions here is it is specific to Nuxt 3 performance as well.

We are in the middle of upgrading our app from Nuxt 2 -> 3. We successfully use nuxt-speedkit for our current Nuxt 2 app.  We do not use all the features, mainly the basic setup which does a great job for the module Lighthouse scores. 

**Nuxt 2 Setup**
```
[
      'nuxt-speedkit',
      {
        speedkit: {
          disableNuxtImage: true,
          detection: {
            performance: true,
            browserSupport: true,
          },
          performanceMetrics: {
            device: {
              hardwareConcurrency: { min: 2, max: 48 },
              deviceMemory: { min: 2 },
            },
            timing: {
              fcp: 800,
              dcl: 1200,
            },
          },
          componentAutoImport: false,
          componentPrefix: undefined,
          lazyOffset: {
            component: '0%',
            asset: '0%',
          },
        },
      },
    ],
//Extras for reference:
    [
      'nuxt-compress',
      {
        gzip: { threshold: 8192 },
        brotli: { threshold: 8192 },
      },
    ],
  purgeCSS: {
    mode: 'postcss',
    paths: [
      'node_modules/bootstrap-vue/es/**/**/*.js',
      'node_modules/bootstrap-vue/**/*.js',
    ],
    styleExtensions: ['.css'],
    whitelist: ['blockquote', 'adblock', 'figure', 'figcaption'],
    whitelistPatterns: [
      /^b-/,
      /nav/,
      /^col-/,
      /icon/,
      /^offset-/,
      /^alert/,
      /^multiselect/,
      /^toasted/,
      /^bs-tooltip/,
      /^aud-/,
    ],
    whitelistPatternsChildren: [
      /article-content$/,
      /media--type-image$/,
      /gallery$/,
      /videos$/,
      /jwplayer$/,
    ],
  },
  build: {
    babel: {
      compact: true,
    },
    extractCSS: true,
    loaders: {
      limit: 0,
    },
  },
  fontLoader: {
    url: '/css/fonts.css',
    prefetch: true,
    preconnect: true,
  },
```

**Nuxt 2 Scores**
Mobile: on average we get between 92 - 100
Desktop: 100.
We get these results locally and in production

---

**Nuxt 3 setup** (Nuxt 3.5.3 with Nitro 2.4.1)
First up you need nitro adding to your config otherwise your results will be poor to start with.

```
nitro: {
  compressPublicAssets: true,
},
```

Results without speedkit:
74 - 80

Let's add in nuxt-speedkit now:

```
[
      'nuxt-speedkit',
      {
        speedkit: {
          detection: {
            performance: true,
            browserSupport: true,
          },
          performanceMetrics: {
            device: {
              hardwareConcurrency: { min: 2, max: 48 },
              deviceMemory: { min: 2 },
            },
            timing: {
              fcp: 800,
              dcl: 1200,
            },
          },
          componentAutoImport: false,
          componentPrefix: undefined,
          /**
           * IntersectionObserver rootMargin for Compoennts and Assets
           */
          lazyOffset: {
            component: '0%',
            asset: '0%',
          },
        },
      },
    ],
// Extras for reference
[
      'nuxt-purgecss',
      {
        enabled: false,
        content: [
          'node_modules/bootstrap-vue-next/**/**/*.js',
          'node_modules/bootstrap-vue-next/**/*.js',
        ],
        safelist: {
          standard: [],
          deep: [],
          greedy: [],
          keyframes: [],
          variables: [],
        },
      },
    ],
lazyLoad: {
    // These are the default values
    images: true,
    videos: true,
    audios: true,
    iframes: true,
    native: false,
    directiveOnly: true,

    // Default image must be in the public folder
    defaultImage: '/images/default-image.jpg',

    // To remove class set value to false
    loadingClass: 'isLoading',
    loadedClass: 'isLoaded',
    appendClass: 'lazyLoad',

    observerConfig: {
      // See IntersectionObserver documentation
    },
  },
  fontLoader: {
    local: [
      {
        src: '/fonts/raleway-v19-latin/raleway-v19-latin-100.woff2',
        family: 'Raleway',
        weight: '100',
        style: 'normal',
        display: 'swap',
        class: 'raleway-100',
      },
      {
        src: '/fonts/raleway-v19-latin/raleway-v19-latin-600.woff2',
        family: 'Raleway',
        weight: '600',
        style: 'normal',
        display: 'swap',
        class: 'raleway-600',
      },
      {
        src: '/fonts/raleway-v19-latin/raleway-v19-latin-300italic.woff2',
        family: 'Raleway',
        weight: '300',
        style: 'italic',
        display: 'swap',
        class: 'raleway-300-italic',
      },
      {
        src: '/fonts/roboto-slab-variable.woff2',
        family: 'Roboto Slab',
        weight: '200 300 400 500',
        style: 'normal',
        display: 'swap',
        class: 'roboto-slab-200',
      },
      {
        src: '/fonts/roboto-v27-latin/roboto-v27-latin-italic.woff2',
        family: 'Roboto',
        weight: '400',
        style: 'italic',
        display: 'swap',
        class: 'roboto-italic',
      },
      {
        src: '/fonts/roboto-v27-latin/roboto-v27-latin-regular.woff2',
        family: 'Roboto',
        weight: '400',
        style: 'normal',
        display: 'swap',
        class: 'roboto-regular',
      },
    ],
  },
```

run: `pnpm build && pnpm preview`

Results: Mobile: 75 average.

Are we missing something? Again I am aware that we are not using all the features, but we don't in Nuxt 2 and benefit so much from it.

Any help or suggestions would be awesome.

**Comment by ThornWalli** [comment]
@StirStudios, how does your network compare to nuxt@2?

This must be clean to get changes, for this the correct loading of the resources is essential. 

**Important:** The first `entry.xxx.js` script initializes the client, everything after that will be reloaded. This should not happen in the mobile lighthouse. Therefore the question what else is in the network?

With JS:
![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/8287751/ae3eceaf-a494-4e82-be73-18f66b5480e3)

Without JS:
![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/8287751/0121f51a-e397-43e7-bdf9-beb6b1e2df55)

**Comment by mhaziq-grayphite** [comment]
Hi @ThornWalli, Sorry for getting back so late. 
You're right we have pretty big files but nuxt3 with vite handeling it well on desktop. I'm not sure I follow `exchange vnode takes quite long`. can you elaborate more.

and So you're saying we have to wait until nuxt-speedkit for nuxt3 completes? 

one more question is there a way I can use this library only on mobile case as I am already getting 80+ score using nuxt3 with vite. but for mobile this module made an impressive improvement.

**Comment by muhammad-grayphite** [comment]
Hi @ThornWalli, Sorry for getting back so late.
You're right we have pretty big files but nuxt3 with vite handeling it well on desktop. I'm not sure I follow `exchange vnode takes quite long`. can you elaborate more.

and So you're saying we have to wait until nuxt-speedkit for nuxt3 completes?

one more question is there a way I can use this library only on mobile case as I am already getting 80+ score using nuxt3 with vite. but for mobile this module made an impressive improvement.

**Comment by StirStudios** [comment]
@ThornWalli thanks for all the info.

One interesting thing I have noticed is that the FCP and LCP is really bad when I test Nuxt 3. Also this has only been tested locally. I think either I have a terrible setup locally (same as Nuxt 2 though) or the build/preview is not being done correctly to test performance. For Nuxt 2 we would usually run `build` and then `start`. For N3 we run `build` and then `preview`.

![SCR-20230619-mjof](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/25397758/e515d0a1-23f7-4014-ac45-ee59cd4485bd)

The network looks pretty good from what I can see.

As I said FCP and LCP is good with Nuxt 2 on a local test. So it makes me wonder there is something else going on.

If we do not have nitro compress on the scroes are really bad. Without nitro we average 62. So back to the setup I think?

**Comment by ThornWalli** [comment]
@StirStudios  Can this be closed?

**Comment by StirStudios** [comment]
Yeah I think so. This was for a much bigger project and migrating from Nuxt 2 -> Nuxt 3. I have not had a chnace to go back in and run further tests.

**Comment by muhammad-grayphite** [comment]
Actually I did solve this issue by using Vue3 defineAsyncComponent. I was using `speedkitHydrate ` for dynamic components like 
`components: {
    A: speedkitHydrate(() => import('@/components/A.vue')),
  }`
  I replace it with defineAsyncComponent for all of the components and worked. I feel like lazy loading with defineAsyncComponent is way more impressive, however speedkit benefitted us on mobile a lot.

**Comment by ThornWalli** [comment]
The only difference here is that when using SpeedkitHydrate the initialization in the client takes place in the viewport. 

Of course, this can lead to problems if it is not in the viewport.

https://github.com/GrabarzUndPartner/nuxt-speedkit/blob/5321d61995ae9752212f99caa29e5bb2679b19f5/src/runtime/hydrate.mjs#L7-L22C3

**Comment by ThornWalli** [comment]
I'm closing this issue for now.
Let me know if this problem still exists 🙃
