### ISSUE TITLE
ERROR  Error while requiring module nuxt-speedkit: TypeError: _consola.default.withTag is not a function 

### ISSUE THREAD

**Issue by learntheropes** [basics/nuxt-booster#842]
**Describe the bug**
The app does not build correctly due to an error,
The error is: 
```
ERROR  Error while requiring module nuxt-speedkit: TypeError: _consola.default.withTag is not a function 
```
**To Reproduce**
1. Install the package
2. Copy the doc default settings in your project
3. Run `npm run dev`

**Expected behavior**
The app should build without any error, as it does without this module.

**Desktop (please complete the following information):**
 - Browser [e.g. brave.]
 - Version [e.g. 1.56.11]

**Comment by ThornWalli** [comment]
Hello @learntheropes ,

Which `nuxt` and `node` version are you using? 

It is quite strange, could you put the dependency `consola` in your build trnaspile?

e.g. `build.transpile = ['consola'];`

**Comment by learntheropes** [comment]
When I opened the issue, I was with `node 16.x` with `nuxt 3.6.5`.

I just tested again with:
```
------------------------------
- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      $production, app, runtimeConfig, css, components, modules, robots, sitemap, content, i18n, image, nitro, speedkit, delayHydration, build, appConfig
- Runtime Modules:  nuxt-simple-robots@3.1.2, nuxt-simple-sitemap@3.2.6, @nuxt/content@2.6.0, @nuxtjs/i18n@8.0.0-beta.12, @nuxt/image@1.0.0-rc.1, nuxt-icons@3.2.1, nuxt-speedkit@2.2.3, nuxt-delay-hydration@1.2.1
- Build Modules:    -
------------------------------
```
And I have the same issue.

` build: { transpile: ['consola']}` does not fix it.`

Now I'm with `nuxt-speedkit 2.2.3` and I guess it was the same when I tested the first time.

**Comment by ThornWalli** [comment]
@learntheropes Can you check which version `node_modules/consola` has in your project?

**Comment by ThornWalli** [comment]
This is a version 2 problem, it is no longer maintained.
