### ISSUE TITLE
SpeedKit Image issue in getImageSize function

### ISSUE THREAD

**Issue by alghifarifikri** [basics/nuxt-booster#887]
**Describe the bug**
I got several issues when use `  <speedkit-image />`.

1. getImageSize: https://{IMAGE_URL} TypeError [ERR_INVALID_ARG_TYPE]: The "obj" argument must be an instance of Blob. Received an instance of Blob
2. getImageSize: https://{IMAGE_URL} FetchError:  (404 Not Found (https://{IMAGE_URL})) **(In Docker Swarm)**
3. getImageSize: https://{IMAGE_URL} TypeError :  body used already for: https://{IMAGE_URL} **(In Docker Swarm)**

**To Reproduce**

1. Install the package
2. use speedkit image 
`  <speedkit-image  v-bind="image" @load="onLoadImage" />`
`image: {
        source: {
          format: 'webp',
          src: this.url,
          sizes: { default: '100vw', xxs: '100vw', xs: '100vw', sm: '100vw', md: '100vw', lg: '100vw', xl: '100vw', xxl: '100vw' }
        },
        title: this.title,
        alt: this.alt,
      }`
3. Run npm run dev

**Expected behavior**
The images loaded successfully, and did not cause any errors, especially when using Google Lighthouse.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by ThornWalli** [comment]
Hello @alghifarifikri,

which `node` version and `nuxt` are you using?

**Comment by alghifarifikri** [comment]
> Hello @alghifarifikri,
> 
> which `node` version and `nuxt` are you using?

Hello @ThornWalli 
I'm using node v16.16.0

**Comment by ThornWalli** [comment]
Can you update your `node` to a newer version?

**Comment by alghifarifikri** [comment]
> @alghifarifikri Can you update your `node` to a newer version?

@ThornWalli I haven't tried it, is the solution just to upgrade the node version ?

**Comment by alghifarifikri** [comment]
> @alghifarifikri Can you update your `node` to a newer version?

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/55394674/31da6061-2a07-4052-a441-477de233a6f0)
I'm try to update node to newer version and still error.

**Comment by ThornWalli** [comment]
Which node version did you go to?

I tested the project myself under Windows 10 with Node 19.9.0 and it runs as expected. 

Your error message may be due to an outdated node version being used. 

There were a few changes between Node 16 and 19.

**Comment by alghifarifikri** [comment]
> Which node version did you go to?
> 
> I tested the project myself under Windows 10 with Node 19.9.0 and it runs as expected.
> 
> Your error message may be due to an outdated node version being used.
> 
> There were a few changes between Node 16 and 19.

I'm using node version 20, do I need to downgrade again?

**Comment by ThornWalli** [comment]
Extremely strange...

I also tested again with Node `20.9.0` and no problems...

Ran without problems, in the project repo and in a project with an installed package.

Could you share your installed dependency and the `nuxt.config`?

**Comment by alghifarifikri** [comment]
> Extremely strange...
> 
> I also tested again with Node `20.9.0` and no problems...
> 
> Ran without problems, in the project repo and in a project with an installed package.
> 
> Could you share your installed dependency and the `nuxt.config`?

this is my `dependency`
![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/55394674/72c3f6e7-3d1d-4409-b056-354b45a6fc6e)

this is my `nuxt.config` for `nuxt-speedkit`
![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/55394674/56feab29-0021-47bc-b1ee-a95a04940c32)
![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/55394674/dced8dc3-c1f3-45b5-81c2-8a325d6647cb)

Let me know if anything is missing or wrong.

**Comment by ThornWalli** [comment]
I'm closing this issue for now.
Let me know if this bug still exists 🙃
