### ISSUE TITLE
Migrating from nuxt-speedkit to nuxt-booster

### ISSUE THREAD

**Issue by Emili-HD** [basics/nuxt-booster#983]
I am trying to migrate from nuxt-speedkit to nuxt-booster. When I update the dependencies and try to start Nuxt, I get the following error:

Cannot restart nuxt: ENOENT: no such file or directory, open '/Applications/MAMP/htdocs/myapp-nuxt/node_modules/nuxt-booster/dist/media/video.mp4'

**Comment by ThornWalli** [comment]
Hello @Emili-HD,

you can look again 😉

Problem should be fixed.

**Comment by liquidiert** [comment]
@ThornWalli why have you added the .mp4 file anyway?

**Comment by ThornWalli** [comment]
@liquidiert Part of the check whether the device is in energy-saving mode.

You can ignore the check here https://basics.github.io/nuxt-booster/guide/options.html#detection

This is a small empty video that is only used to check whether the video container is autostarting or not.

**Comment by liquidiert** [comment]
Ah okay makes sense, thank you!

**Comment by Emili-HD** [comment]
Run like a charm! Thanks!
