### ISSUE TITLE
`targetFormats` appears to be an invalid config prop

### ISSUE THREAD

**Issue by armenr** [basics/nuxt-booster#989]
**Describe the bug**
Attempting to use `targetFormats` throws TypeScript error: `Type 'string[]' is not assignable to type 'undefined'.ts(2322)`

**To Reproduce**
1. Install nuxt-booster
2. Paste the configuration example provided in the docs
3. Observe issues with the config...

**Expected behavior**
Expectation would be that the config example provided in the docs would not throw typescript/type errors.

**Screenshots**
![Screenshot 2024-04-24 at 10 15 22 PM](https://github.com/basics/nuxt-booster/assets/7662191/f7758c02-943b-4662-9077-481363fc4c52)

**Comment by ThornWalli** [comment]
@armenr There is an update for this, had an undefined in the `default` of the module options, replaced it with a `[]`.

Hope this fixes the message.
